config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about_us', to: 'pages#about_us'
  get '/contact', to: 'pages#contact'
  get '/faq', to: 'pages#faq'
  get '/how_it_works', to: 'pages#how_it_works'
  get '/soldout', to: 'pages#soldout'
  get '/terms', to: 'pages#terms'
  get '/testimonials', to: 'pages#testimonials'

  resources :choices
  resources :travelers
  resources :cities
  resources :reservations do
    member do
      get :travelers
    end
  end

  devise_for :users

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :reservation
  belongs_to :city 
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only: [:show, :edit, :update, :destroy]

  # GET /choices
  # GET /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(choice_params)

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render :show, status: :created, location: @choice }
      else
        format.html { render :new }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choices/1
  # PATCH/PUT /choices/1.json
  def update
    respond_to do |format|
      if @choice.update(choice_params)
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @choice }
      else
        format.html { render :edit }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice.destroy
    respond_to do |format|
      format.html { redirect_to choices_url, notice: 'Choice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choice
      @choice = Choice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choice_params
      params.require(:choice).permit(:name, :reservation_id, :city_id)
    end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_for(@choice) do |f| %>
  <% if @choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% @choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reservation_id %><br>
    <%= f.number_field :reservation_id %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.number_field :city_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Choices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Chosen</th>
      <th>Reservation</th>
      <th>City ID</th>
      <th>City Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= choice.name %></td>
        <td><%= choice.chosen %></td>
        <td><%= choice.reservation_id %></td>
        <td><%= choice.city_id %></td>
        <td> <% if !choice.city.nil? %> <%= choice.city.name %>  <%end%></td>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @choice.name %>
</p>

<p>
  <strong>Reservation:</strong>
  <%= @choice.reservation_id %>
</p>

<p>
  <strong>City:</strong>
  <%= @choice.city_id %>
</p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>