config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/about_us', to: 'pages#about_us'
  get '/contact', to: 'pages#contact'
  get '/faq', to: 'pages#faq'
  get '/how_it_works', to: 'pages#how_it_works'
  get '/soldout', to: 'pages#soldout'
  get '/terms', to: 'pages#terms'
  get '/testimonials', to: 'pages#testimonials'

  resources :choices
  resources :travelers
  resources :cities
  resources :reservations do
    member do
      get :travelers
    end
  end

  devise_for :users

end

app/views/layouts/_home_footer.html.erb
<footer class="container-fluid">
	<div class="container-footer-responsive md-margin-top">
		<div class="row">
			<div class="col-sm-4">
				<div class="footer-col">
					<ul class="list-layout-footer">
						<li><%= image_tag("logo-white.png") %></li>
						<li class="sm-margin-top sm-margin-left"><b>Hewago.com</b><br>15 rue Ferdinand Buisson<br>92110 Clichy</li>
					</ul>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="footer-col">
					<h2 class="sm-margin-left">Société</h2>
					<ul class="list-layout-footer sm-margin-left">
						<li><%= link_to "Qui sommes nous?", about_us_path %></li>
						<li><%= link_to "Aide - FAQ", faq_path %></li>
						<li><%= link_to "Conditions générales et confidentialité", terms_path %></li>
						<li><%= link_to "Contact", contact_path %></li>
					</ul>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="footer-col">
					<h2 class="sm-margin-left">Découvrir</h2>
					<ul class="list-layout-footer sm-margin-left">
						<li><%= link_to "Comment ça marche?", how_it_works_path %></li>
						<li><%= link_to "Témoignages de nos aventuriers", testimonials_path %></li>
					</ul>
				</div>
			</div>
		</div>
		<hr class="divider-footer" />
		<div class="text-center">
			<h2>Rejoins-nous sur</h2>
			<ul class="footer-menu-social">
				<li><a href="https://www.facebook.com/hewago" target="_blank"><i class="fa fa-facebook"></i></a></li>
				<li><a href="https://twitter.com/hewago_" target="_blank"><i class="fa fa-twitter"></i></a></li>
				<li><a href="https://www.instagram.com/hewago" target="_blank"><i class="fa fa-instagram"></i></a></li>
			</ul>
			<p class="copywright-footer">&copy; 2016 Hewago &middot; Tous droits réservés</p>
		</div>
	</div>
</footer>

app/views/layouts/_home_header.html.erb
<header class="main-menu">
  <%= link_to image_tag("menu-burger.png"), "#", class:"header-icon", id:"header-icon" %>
  <div class="header-pull-left">
      <%= link_to image_tag("logo.png"), root_path %>
  </div>

  <ul class="header-pull-right">
      <li><%= link_to "Comment ça fonctionne ?", how_it_works_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
  </ul>
</header>
<ul class="menu-responsive-header">
  <li><%= link_to 'Accueil', root_path, class:"sm-margin-top" %></li>
  <li><%= link_to "Comment ça fonctionne ?", how_it_works_path %></li>
  <li><%= link_to "FAQ", faq_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Ton week-end dans une destination surprise dès 175€ - Hewago</title>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
		<!--[if lte IE 8]>
		<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
		<![endif]-->

	<meta content="text/html;charset=utf-8" http-equiv="Content-Type" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%flash.each do |name, msg| %>
    <%= content_tag(:div,msg,class:"alert alert-info") %>
  <%end%>

  <%= render 'layouts/home_header' %>
  <%= yield %>
  <%= render 'layouts/home_footer' %>

  <div class="site-hidden" id="site-hidden"></div>

</body>
</html>